CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(255) NOT NULL
);


INSERT INTO users (username, password, role)
VALUES ('admin', '$2a$10$P1jlbxpYTw5GPFCcTgN1eeeXKinHWmEuM/VPIwBzN2eVFMY4rZ0ly', 'admin');

INSERT INTO users (username, password, role)
VALUES ('user', '$2a$10$nRgYpOhpCL/07XihlLiTvu8e/5f91GJtYL9/bO8BVuAjcbplIcdmy', 'user');